[tox]
env_list = py312
skipsdist = true

[testenv]
skip_install = true
deps = -r requirements-dev.txt
commands = pytest {posargs}
passenv =
    PIP_NO_INDEX
    PIP_FIND_LINKS
    PIP_DISABLE_PIP_VERSION_CHECK

[testenv:py312-cov]
skip_install = true
deps =
    -r requirements-dev.txt
    pytest-cov>=5.0.0
commands = pytest --cov=. --cov-report=term-missing {posargs}
passenv =
    PIP_NO_INDEX
    PIP_FIND_LINKS
    PIP_DISABLE_PIP_VERSION_CHECK
